"""add_telegram_monitored_chats_table

Revision ID: 141322db7875
Revises: telegram_configs_manual
Create Date: 2025-09-23 19:22:57.377387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141322db7875'
down_revision: Union[str, Sequence[str], None] = 'telegram_configs_manual'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_monitored_chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_config_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=255), nullable=False),
    sa.Column('chat_title', sa.String(length=255), nullable=True),
    sa.Column('chat_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['telegram_config_id'], ['telegram_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_monitored_chats')
    # ### end Alembic commands ###
