"""change base models

Revision ID: 63b2e32b0bb5
Revises: cf87f9f50663
Create Date: 2025-09-20 16:49:16.395063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63b2e32b0bb5'
down_revision: Union[str, Sequence[str], None] = 'cf87f9f50663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_logs', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.drop_column('agent_logs', 'update_at')
    op.alter_column('agents', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('agents', 'update_at')
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('documents', 'update_at')
    op.add_column('plans', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.alter_column('plans', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('plans', 'update_at')
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.drop_column('subscriptions', 'update_at')
    op.drop_column('user_agents', 'update_at')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'update_at')
    op.add_column('wallet_deposits', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.drop_column('wallet_deposits', 'update_at')
    op.add_column('wallets', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.drop_column('wallets', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('update_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False))
    op.drop_column('wallets', 'updated_at')
    op.add_column('wallet_deposits', sa.Column('update_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False))
    op.drop_column('wallet_deposits', 'updated_at')
    op.add_column('users', sa.Column('update_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.add_column('user_agents', sa.Column('update_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('update_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False))
    op.drop_column('subscriptions', 'updated_at')
    op.add_column('plans', sa.Column('update_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False))
    op.alter_column('plans', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('plans', 'updated_at')
    op.add_column('documents', sa.Column('update_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False))
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('documents', 'updated_at')
    op.add_column('agents', sa.Column('update_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False))
    op.alter_column('agents', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('agent_logs', sa.Column('update_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False))
    op.drop_column('agent_logs', 'updated_at')
    # ### end Alembic commands ###
