"""add_user_id_to_agent_logs

Revision ID: 79e78b83ff1c
Revises: 22054f80c94b
Create Date: 2025-09-04 13:35:38.806277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e78b83ff1c'
down_revision: Union[str, Sequence[str], None] = '22054f80c94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_logs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'agent_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_logs', type_='foreignkey')
    op.drop_column('agent_logs', 'user_id')
    # ### end Alembic commands ###
