"""add new tables

Revision ID: cf87f9f50663
Revises: add_telegram_configs
Create Date: 2025-09-20 15:22:54.416948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf87f9f50663'
down_revision: Union[str, Sequence[str], None] = 'add_telegram_configs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_configs_agent_id'), table_name='telegram_configs')
    op.drop_index(op.f('ix_telegram_configs_is_active'), table_name='telegram_configs')
    op.drop_index(op.f('ix_telegram_configs_user_id'), table_name='telegram_configs')
    op.drop_table('telegram_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bot_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_telegram_configs_agent_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_telegram_configs_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('telegram_configs_pkey'))
    )
    op.create_index(op.f('ix_telegram_configs_user_id'), 'telegram_configs', ['user_id'], unique=False)
    op.create_index(op.f('ix_telegram_configs_is_active'), 'telegram_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_telegram_configs_agent_id'), 'telegram_configs', ['agent_id'], unique=False)
    # ### end Alembic commands ###
